### ISSUE TITLE
(SP: 2) Implement General Info step

### ISSUE THREAD

**Issue by nrevutska** [WebUI-Project-Based-10-nr/Client#19]
**User Stories #77, #74**
## Description
Implement the general info step to used it in both student and tutor cause they are the same according to the mockup.

## Design 

![Image](https://github.com/ita-social-projects/Space2Study-node-Client-mvp/assets/110425368/2bfc7e20-129e-49f0-9518-98c2fa472b2b)

## Acceptance Criteria
- [ ] First name and Last name of a user should be pulled from first registration form.
- [ ] Country and city have to be pulled from server on input focus
- [ ] Additional info length can't be more than 70 symbols

**Comment by petro97** [comment]
I can't complete pulling Countries and cities from the server since there are no endpoints for this yet. Also, we have a separate ticket for that on the Client. https://github.com/WebUI-Project-Based-10-nr/Client/issues/10
